apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: curl-config-refresh
spec:
  description: >-
    This task performs curl operation to transfer data from internet.
  params:
    - name: url
      description: URL to be curl'ed
      type: string
    - name: options
      description: options of url
      type: array
      default: []
    - name: curl-image
      description: option of curl image
      type: string
      default: "docker.io/curlimages/curl:7.72.0@sha256:3c3ff0c379abb1150bb586c7d55848ed4dcde4a6486b6f37d6815aed569332fe" #tag: 7.72.0
  steps:
    - name: curl
      image: "$(params.curl-image)"
      command: [curl]
      args: ["$(params.options[*])", "$(params.url)"]
      env:
        - name: HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: catalog-refresh
              key: HUB_TOKEN
