apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: config-refresh-template
  annotations:
    triggers.tekton.dev/old-escape-quotes: "true"
spec:
  params:
    - name: commits
      description: The commits which got pushed
    - name: gitRepository
      description: The git repository that hosts context and Dockerfile
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: config-refresh-run-
        annotations:
          tekton.dev/gitURL: "$(tt.params.gitRepository)"
      spec:
        pipelineRef:
          name: config-refresh-pipeline
        params:
          - name: commits
            value: "$(tt.params.commits)"
          - name: filename
            value: "config.yaml"
          - name: urlToCurl
            value: api:8000/system/config/refresh
          - name: options
            value:
              ["-i", "-k", "-X", "POST", "-H", "Authorization:$(HUB_TOKEN)"]
